/**
 * Matriz de Graduação Kingdom Fight (Muay Thai) — fonte: "Graduação Kingdom.docx".
 * Usada pelo admin para importar o modelo numa modalidade (o conteúdo é depois editável).
 * Cada grau descreve o que o aluno precisa para OBTER esse grau.
 */

import type { GraduationAxis, GraduationTemplateDraft } from "./template";

/** Texto simples, ou [rótulo, descrição] quando o documento detalha sub-itens. */
type SeedItem = string | [string, string];

type SeedGrade = {
  name: string;
  subtitle: string;
  motto: string;
  objective: string;
  notes?: string;
  colors: string[];
  minMonths: number;
  axes: Record<GraduationAxis, SeedItem[]>;
  requirements?: string[];
};

const C = {
  branco: "#F5F5F5",
  laranja: "#F97316",
  azulCeleste: "#38BDF8",
  roxo: "#7C3AED",
  verdeLimao: "#84CC16",
  preto: "#111111",
  prata: "#A8A9AD",
  vermelho: "#DC2626",
};

export const KINGDOM_MUAY_THAI_GRADES: SeedGrade[] = [
  {
    name: "Branco",
    subtitle: "Pureza e Início",
    motto: "Eu começo.",
    objective: "Adaptação corporal, postura, guarda e fundamentos de proteção.",
    colors: [C.branco],
    minMonths: 3,
    axes: {
      TECNICO: [
        "Guarda básica",
        "Postura e base",
        "Distribuição básica de peso",
        "Alinhamento de pés, joelhos, quadril e tronco",
        "Jab",
        "Direto",
        "Frontal / Teep",
        "Guarda alta",
        "Bloqueio básico",
        "Checagem simples de chute",
        "Passada à frente e atrás",
        "Deslocamento lateral",
        "Pivot básico",
        "Retorno à guarda após executar golpes",
        "Combinações simples de 1–2 ações",
      ],
      TATICO: [
        "Noção de distância longa e média",
        "Identificação básica da distância adequada para atacar",
        "Manter a guarda durante o combate",
        "Reconhecer ataque simples do adversário",
        "Começar a diferenciar ataque, defesa e contra-ataque",
      ],
      TEORICO: [
        "Código de conduta da academia",
        "Respeito aos colegas e instrutores",
        "Nomenclatura básica",
        "Conceito de disciplina",
        "Conceito de respeito",
        "Conceito de humildade",
        "Regras básicas de segurança",
        "Equipamentos básicos",
      ],
      FISICO: [
        "Mobilidade básica",
        "Coordenação motora básica",
        "Equilíbrio",
        "Estabilidade de base",
        "Resistência aeróbica inicial",
        "Capacidade de realizar rounds curtos",
        "Resistência muscular básica",
        "Controle respiratório",
        "Capacidade de manter postura durante esforço",
      ],
    },
  },
  {
    name: "Branco/Laranja",
    subtitle: "Despertar da Vontade",
    motto: "Eu me comprometo.",
    objective: "Primeiras conexões de golpes, esquivas e rotações.",
    colors: [C.branco, C.laranja],
    minMonths: 3,
    axes: {
      TECNICO: [
        "Hook",
        "Uppercut",
        "Roundhouse Kick",
        "Esquiva pendular",
        "Esquiva lateral",
        "Defesa contra golpes retos",
        "Bloqueio → contra-ataque",
        "Checagem → contra-ataque",
        "Combinações de 2–3 golpes",
        "Rotação correta do tronco",
        "Uso dos pés na geração de força",
        "Introdução ao deslocamento durante ataques",
      ],
      TATICO: [
        "Entender que nem todo movimento exige ataque",
        "Reação sob estresse controlado",
        "Primeira leitura mecânica do ataque",
        "Identificar golpes previsíveis",
        "Escolher entre bloquear, esquivar ou sair",
        "Introdução ao conceito de timing",
      ],
      TEORICO: [
        "Os 5 pilares da Kingdom Fight",
        "História básica da modalidade",
        ["Nomenclatura das armas do corpo", "Mãos, cotovelos, joelhos, canelas/pés."],
        "Alavanca",
        "Equilíbrio",
        "Centro de gravidade",
        "Rotação",
        "Transferência de peso",
        "Diferença básica entre força e velocidade",
        "Princípios básicos de segurança no contato",
      ],
      FISICO: [
        "Desenvolvimento de resistência muscular",
        "Coordenação intermuscular",
        "Mobilidade de quadril e ombro",
        "Resistência aeróbica",
        "Introdução à potência",
        "Capacidade de sustentar rounds moderados",
        "Recuperação entre rounds",
        "Controle respiratório durante combinações",
      ],
    },
  },
  {
    name: "Laranja",
    subtitle: "Energia e Entusiasmo",
    motto: "Eu desenvolvo.",
    objective: "Consolidação dos 8 membros, volume e resistência.",
    colors: [C.laranja],
    minMonths: 4,
    axes: {
      TECNICO: [
        "Joelhada reta",
        "Switch Kick",
        "Combinações de 3–4 golpes",
        "Mudança de níveis",
        "Combinação mão → perna → mão",
        "Ataques ao tronco, cabeça e pernas",
        "Clinch inicial",
        "Controle básico da nuca",
        "Defesa de postura no clinch",
        "Técnicas executadas em movimento",
        "Combinações sob fadiga moderada",
      ],
      TATICO: [
        "Manter os olhos abertos diante de impacto controlado",
        "Reconhecimento da intenção do adversário",
        "Gestão de fôlego em rounds de saco/manopla",
        "Começar a controlar o ritmo do próprio trabalho",
        "Não gastar energia desnecessariamente",
        "Ritmo",
        "Volume",
        "Capacidade de impor ritmo no saco e manoplas",
        "Manter qualidade técnica sob volume",
      ],
      TEORICO: [
        "Biomecânica da produção de força",
        ["Força partindo do solo", "Cadeia cinética."],
        "Transferência pelo quadril",
        "Rotação corporal",
        "Cadeia cinética básica",
      ],
      FISICO: [
        "Resistência anaeróbica inicial",
        "Resistência muscular específica",
        "Capacidade de manter volume de golpes",
        "Desenvolvimento de potência",
        "Coordenação em alta velocidade",
        "Capacidade de realizar rounds maiores",
        "Tolerância progressiva à fadiga",
        "Recuperação entre esforços intensos",
      ],
    },
  },
  {
    name: "Laranja/Azul Celeste",
    subtitle: "Equilíbrio em Formação",
    motto: "Eu controlo.",
    objective: "Transição da força para o controle tático e domínio dos ângulos.",
    colors: [C.laranja, C.azulCeleste],
    minMonths: 5,
    axes: {
      TECNICO: [
        "Cotovelada lateral",
        "Cotovelada frontal",
        "Saída lateral",
        "Ataque saindo da linha de confronto",
        "Parry",
        "Catch",
        "Varreduras básicas",
        "Low Kick de encontro",
        "Combinações com mudança de ângulo",
        "Defesa ativa",
        "Contra-ataque após defesa",
      ],
      TATICO: [
        "Introdução ao sparring condicionado",
        "Tomada de decisão dentro de regras limitadas",
        "Entender quando aumentar ou diminuir o ritmo",
        "Começar a reconhecer padrões simples de reação",
        "Contra-golpe",
        "Timing",
        "Esperar a ação do adversário",
        "Responder no momento adequado",
        "Economia de energia",
        "Saber acelerar",
        "Saber cadenciar",
        "Controle básico da distância",
        "Utilizar ângulo para criar vantagem",
        "Começar a provocar erros no adversário",
      ],
      TEORICO: [
        "Assistência ao professor nas aulas",
        "Regras básicas do combate desportivo",
        "Pontuação",
        "Áreas válidas de golpe",
        "Faltas",
        "Conduta durante sparring",
        "Vetores de ataque",
        "Linhas de ataque",
        "Linhas de corte",
        "Ângulos",
        "Antecipação",
        "Reação tardia",
        "Princípios de contra-ataque",
        "Relação entre distância e tempo de reação",
      ],
      FISICO: [
        "Potência",
        "Velocidade",
        "Agilidade",
        "Mudança rápida de direção",
        "Coordenação sob velocidade",
        "Capacidade anaeróbica",
        "Resistência específica de combate",
        "Manutenção da técnica sob fadiga",
      ],
    },
  },
  {
    name: "Azul Celeste",
    subtitle: "Clareza e Perspicácia",
    motto: "Eu compreendo.",
    objective: "Inteligência tática, leitura de jogo e serenidade no sparring.",
    colors: [C.azulCeleste],
    minMonths: 6,
    axes: {
      TECNICO: [
        "Cotovelada descendente",
        "Cotovelada ascendente",
        "Joelhada saltada/curta",
        "Fintas",
        "Finta de mão → perna",
        "Finta de perna → mão",
        "Switch durante movimentação",
        "Switch durante ataque",
        "Clinch avançado",
        "Projeções simples",
        "Desequilíbrios",
        "Joelhadas laterais",
        "Saídas de clinch sob pressão",
        "Bloqueios dinâmicos",
        "Defesa com antebraços",
        "Combinações condicionadas à reação do adversário",
      ],
      TATICO: [
        "Mapeamento dos vícios do oponente",
        "Identificação de padrões",
        "Controle do centro",
        "Controle da área de combate",
        "Exploração de hábitos",
        "Controle de distância",
        "Manipulação de ritmo",
        "Criação de situações favoráveis",
        "Tomada de decisão em sparring aberto",
      ],
      TEORICO: [
        ["Sistemas energéticos", "Aláctico, láctico e aeróbico."],
        "Preparação física específica para esportes de combate",
        "Arbitragem",
        "Critérios de julgamento",
        "Pontuação",
        "Estratégias básicas de vitória por rounds",
        "Diferenças entre estilos de combate",
      ],
      FISICO: [
        "Desenvolvimento equilibrado de força, potência e resistência",
        "Velocidade de reação",
        "Agilidade",
        "Resistência anaeróbica",
        "Capacidade de repetir esforços explosivos",
        "Recuperação entre esforços",
        "Tolerância ao sparring",
        "Manutenção da técnica sob fadiga elevada",
      ],
    },
  },
  {
    name: "Azul/Roxo",
    subtitle: "Transição Estratégica",
    motto: "Eu conecto.",
    objective: "Encadeamento com intenção, quebra de ritmo e armadilhas táticas.",
    colors: [C.azulCeleste, C.roxo],
    minMonths: 6,
    axes: {
      TECNICO: [
        "Combinações complexas",
        "Combinações assimétricas",
        ["Mudanças de velocidade", "Lento → rápido → explosivo."],
        "Defesa de clinch sob pressão",
        "Uso de ombro/quadril para criar espaço",
        "Ataques de ângulo cego",
        "Pivot durante golpe",
        "Ataques após criação de ângulo",
        "Sequências com segunda intenção",
        "Integração entre ataque e defesa",
      ],
      TATICO: [
        ["Trapping", "Saber enganar o adversário ou conduzi-lo para qualquer lado do ringue."],
        "Criar brechas propositalmente",
        "Induzir respostas",
        "Contra-atacar a resposta esperada",
        "Sparring contra diferentes biotipos",
        ["Adaptação a diferentes adversários", "Canhotos, atletas mais altos, atletas mais baixos, pressionadores e contra-atacadores."],
        "Quebra de ritmo",
        "Mudança de estratégia durante o round",
      ],
      TEORICO: [
        "Já consegue puxar partes do treino e ensinar novos alunos",
        "Psicologia do combate",
        "Gestão de frustração",
        "Gestão da dor",
        "Gestão da pressão",
        "Tomada de decisão sob estresse",
        "Análise de vídeo",
        "Identificação de padrões técnicos e táticos",
        "Introdução à análise de adversário",
      ],
      FISICO: [
        "Potência específica",
        "Explosividade",
        "Velocidade de reação",
        "Resistência anaeróbica lática",
        "Capacidade de repetir esforços máximos",
        "Tolerância à fadiga",
        "Recuperação rápida",
        "Capacidade de manter tomada de decisão sob exaustão",
      ],
    },
  },
  {
    name: "Roxo",
    subtitle: "Transmutação e Sabedoria",
    motto: "Eu adapto.",
    objective: "Identidade própria de luta e refinamento biomecânico.",
    colors: [C.roxo],
    minMonths: 8,
    axes: {
      TECNICO: [
        "Personalização técnica",
        ["Desenvolvimento de estilo principal", "Muay Mat, Muay Femur, Muay Khao ou outras identidades conforme a modalidade."],
        "Domínio das variações de golpes",
        ["Golpes rodados", "Chute rodado e soco rodado."],
        "Técnicas avançadas",
        "Criação de combinações autorais",
        "Capacidade de justificar tecnicamente suas combinações",
        "Capacidade de demonstrar fundamentos para alunos inferiores",
      ],
      TATICO: [
        "Adaptabilidade em tempo real",
        "Mudança de estratégia durante a luta",
        "Plano A → Plano B",
        "Gestão de tempo",
        "Gestão de pontuação",
        "Gestão de rounds",
        "Adaptação ao estilo do adversário",
        "Exploração sistemática de fraquezas",
        "Preservação das próprias forças",
      ],
      TEORICO: [
        "Metodologia de treino",
        "Elaboração de sessões básicas",
        "Princípios de ensino",
        "Capacidade de instruir iniciantes",
        "Anatomia aplicada ao striking",
        "Pontos vulneráveis",
        "Mecanismos básicos de lesão",
        "Prevenção de lesões",
        "Recuperação",
        "Introdução à análise de desempenho",
      ],
      FISICO: [
        "Força máxima relativa",
        "Potência",
        "Velocidade",
        "Resistência específica",
        "Capacidade de repetir esforços explosivos",
        "Mobilidade funcional",
        "Estabilidade articular",
        "Tolerância a cargas elevadas",
        "Controle do corpo sob fadiga",
      ],
    },
  },
  {
    name: "Roxo/Verde Limão",
    subtitle: "Inovação e Dinamismo",
    motto: "Eu crio.",
    objective: "Alta performance, explosão e preparação competitiva.",
    colors: [C.roxo, C.verdeLimao],
    minMonths: 8,
    requirements: ["Fazer curso intra-corpus de treinador"],
    axes: {
      TECNICO: [
        "Todas as técnicas em alta velocidade",
        "Execução sob fadiga extrema",
        "Ajustes biomecânicos finos",
        "Otimização de trajetória",
        "Otimização de rotação",
        "Economia de movimento",
        "Defesa e contra-ataque instantâneo",
        "Transições entre distâncias",
        "Integração completa das armas",
        "Execução competitiva",
      ],
      TATICO: [
        "High-Tempo Fighting",
        "Controle de ritmo em alta intensidade",
        ["Luta em todas as distâncias", "Longa, média, curta e clinch."],
        "Transições entre distâncias sem quebra de postura",
        "Adaptação em alta velocidade",
        "Gestão de intensidade",
        "Estratégias específicas para competição",
      ],
      TEORICO: [
        "Estratégias de preparação competitiva",
        "Nutrição esportiva",
        "Corte de peso",
        "Reidratação",
        "Periodização",
        "Polimento",
        "Pico de performance",
        "Controle de carga",
        "Recuperação",
        "Preparação pré-competição",
      ],
      FISICO: [
        "Alta potência",
        "Alta velocidade",
        "Força específica",
        "Resistência anaeróbica",
        "Capacidade de repetir esforços máximos",
        "Tolerância a alta intensidade",
        "Recuperação entre rounds",
        "Peak performance",
        "Capacidade de competir em intensidade elevada",
      ],
    },
  },
  {
    name: "Verde Limão/Preto",
    subtitle: "Força Vital Lapidada",
    motto: "Eu lidero.",
    objective: "Preparação para maestria, mentoria e liderança técnica.",
    notes:
      "No físico, o foco deixa de ser apenas o próprio desempenho: o aluno deve compreender e conseguir prescrever cada capacidade física.",
    colors: [C.verdeLimao, C.preto],
    minMonths: 12,
    requirements: ["Ter feito estágio conosco"],
    axes: {
      TECNICO: [
        "Demonstração metodológica",
        "Execução em velocidade lenta",
        "Execução em velocidade máxima",
        "Explicação biomecânica",
        "Identificação de erros",
        "Correção de vícios",
        "Manopla de treinador",
        "Construção de rounds de manopla",
        "Simulação de adversários",
        "Adaptação do treino ao atleta",
        "Ensino técnico",
      ],
      TATICO: [
        "Leitura de corner",
        "Análise de combate",
        "Identificação de problemas durante o round",
        "Instruções entre rounds",
        "Ajuste de estratégia",
        "Identificação de padrões adversários",
        "Construção de plano de combate",
        "Construção de plano alternativo",
        "Desenvolvimento da inteligência tática de outros atletas",
      ],
      TEORICO: [
        "Didática",
        "Pedagogia",
        "Ensino de crianças",
        "Ensino de adultos",
        "Ensino de iniciantes",
        "Ensino de atletas",
        "Gestão de turmas",
        "Segurança no tatame",
        "Primeiros socorros aplicados às artes marciais",
        "Planejamento de treino",
        "Avaliação de atletas",
      ],
      FISICO: [
        "Prescrever força",
        "Prescrever potência",
        "Prescrever velocidade",
        "Prescrever resistência",
        "Prescrever mobilidade",
        "Prescrever agilidade",
        "Condicionamento específico",
        "Controle de carga",
        "Recuperação",
        "Preparação física individualizada",
      ],
    },
  },
  {
    name: "Preto/Prata/Branco/Vermelho",
    subtitle: "Domínio do Reino",
    motto: "Eu formo.",
    objective:
      "Mestre / Professor / Treinador Kingdom Fight. Não avaliamos apenas um atleta, mas alguém capaz de preservar, ensinar, desenvolver e evoluir o sistema Kingdom Fight.",
    notes:
      "Os quatro elementos da graduação máxima:\n" +
      "⚫ Preto — Autoridade: autoridade moral e técnica.\n" +
      "⚙️ Prata — Precisão: ciência, tecnologia, dados e refinamento contínuo.\n" +
      "⚪ Branco — Humildade: mentalidade de eterno aprendiz.\n" +
      "🔴 Vermelho — Paixão e Honra: guardião da cultura, da paixão, da honra e da lealdade ao Reino.\n\n" +
      "No físico, a exigência não é ser o atleta mais condicionado da academia: é conhecer, demonstrar e saber desenvolver as capacidades físicas necessárias para diferentes perfis de lutador.",
    colors: [C.preto, C.prata, C.branco, C.vermelho],
    minMonths: 24,
    requirements: ["Ter feito os cursos Kingdom de treinador e de atletas"],
    axes: {
      TECNICO: [
        "Domínio do acervo técnico da escola",
        "Capacidade de adaptar técnicas para qualquer perfil",
        "Desenvolvimento de novas metodologias",
        "Criação de progressões pedagógicas",
        "Análise biomecânica",
        "Correção técnica",
        "Formação de outros professores",
      ],
      TATICO: [
        "Visão holística do combate",
        "Leitura técnica",
        "Leitura tática",
        "Leitura física",
        "Leitura psicológica",
        "Construção de estratégia",
        "Desenvolvimento de atletas",
        "Análise de adversários",
        "Estratégia competitiva",
        "Capacidade de formar treinadores capazes de pensar taticamente",
      ],
      TEORICO: [
        "Filosofia Kingdom",
        "História e evolução da escola",
        "Pedagogia",
        "Metodologia",
        "Biomecânica",
        "Fisiologia",
        "Psicologia",
        "Análise de desempenho",
        "Ciência do treinamento",
        "Gestão de atletas",
        "Gestão de professores",
        "Ética marcial",
        "Cultura Kingdom Fight",
      ],
      FISICO: [
        "Força",
        "Potência",
        "Velocidade",
        "Resistência aeróbica",
        "Resistência anaeróbica",
        "Agilidade",
        "Mobilidade",
        "Coordenação",
        "Recuperação",
        "Gestão de carga",
        "Prevenção de lesões",
        "Preparação física específica",
        "Individualização do treinamento",
      ],
    },
  },
];

const AXIS_ORDER: GraduationAxis[] = ["TECNICO", "TATICO", "TEORICO", "FISICO"];

/** Constrói um draft do template Kingdom para uma modalidade (ids novos a cada chamada). */
export function buildKingdomTemplateDraft(
  modalityCode: string,
  name: string,
  newId: () => string
): GraduationTemplateDraft {
  return {
    modalityCode,
    name,
    isPublished: false,
    monthlyMinAttendances: 4,
    grades: KINGDOM_MUAY_THAI_GRADES.map((g) => ({
      id: newId(),
      name: g.name,
      subtitle: g.subtitle,
      motto: g.motto,
      objective: g.objective,
      notes: g.notes ?? null,
      colors: g.colors,
      minMonths: g.minMonths,
      minAttendances: null,
      minPerformanceAvg: null,
      physicalAssessmentMaxAgeMonths: 6,
      passMinAxisAvg: 3,
      items: AXIS_ORDER.flatMap((axis) =>
        g.axes[axis].map((item) => {
          const [label, description] = typeof item === "string" ? [item, null] : item;
          return { id: newId(), axis, label, description, isCritical: false };
        })
      ),
      courses: [],
      requirements: (g.requirements ?? []).map((label) => ({ id: newId(), label })),
    })),
  };
}
