/** Condições Gerais de Adesão — Kingdom Fight School (EPICENTRO DE HONRA, LDA). */
export const MEMBERSHIP_AGREEMENT_VERSION = "1";

export const MEMBERSHIP_AGREEMENT_BODY_PT = `
<h2 style="font-size:1.125rem;font-weight:600;margin:16px 0 12px;">Condições Gerais de Adesão Kingdom Fight School</h2>
<p style="margin:0 0 10px;">1.ª - Identificação das PartesO disposto nas presentes condições gerais de adesão é aplicável e rege o contrato celebrado presencialmente entre a EPICENTRO DE HONRA - LDA, pessoa coletiva n.º 519296850, com sede em Praceta Laura Alves 8, 2725-206 Algueirão-Mem Martins, doravante designada por Kingdom Fight School, e o cliente (Sócio/a) devidamente identificado no comprovativo de adesão, relativamente ao acesso e utilização pelo/a Sócio/a das instalações, equipamentos e serviços prestados pela Kingdom Fight School.</p>
<p style="margin:0 0 10px;">2.ª - Objeto2.1 Este contrato tem por objeto o acesso do/a Sócio/a às instalações do(s) ginásios da Kingdom Fight School e à utilização dos respetivos equipamentos e serviços pelo(a) Sócio(a) A Academia presta serviços de ensino e treino de diversas modalidades de artes marciais, acompanhamento técnico e atividades complementares.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">3.º - Regras gerais de Adesão</h3>
<p style="margin:0 0 10px;">A Kingdom Fight School é totalmente livre para a análise, aceitação ou recusa de pedidos de adesão para Sócio(a). A adesão é automaticamente aceite, salvo comunicação escrita em contrário da Kingdom Fight School nos 5 dias posteriores à receção do formulário de adesão. Após a aceitação pela Kingdom Fight School da adesão do(a) Sócio(a), esta considera-se realizada na data da celebração do presente contrato.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">4.ª - Modalidades de Adesão</h3>
<p style="margin:0 0 10px;">4.1.º Modalidades de Adesão. Na data de celebração do Contrato, o/a Sócio/a pode optar por uma das seguintes modalidades de adesão pré-configuradas:</p>
<p style="margin:0 0 10px;">A)Muay Thai</p>
<p style="margin:0 0 10px;">B)Boxe</p>
<p style="margin:0 0 10px;">C) Jiu Jitsu</p>
<p style="margin:0 0 10px;">D) MMA</p>
<p style="margin:0 0 10px;">4.2.º Cada modalidade poderá prever diferentes condições relativas à frequência das aulas, horários, serviços incluídos e valores a pagar. A modalidade escolhida pelo/a Sócio/a ficará identificada na ficha de inscrição, que constitui parte integrante do presente contrato.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">4.3.ª Alterações pelo Sócio/a</h3>
<p style="margin:0 0 10px;">A) É permitido ao/à Sócio/a, a todo o tempo, alterar: - A modalidade de adesão (sem custos adicionais, com exceção do preço que seja devido pelo diferente tipo de modalidade de adesão);</p>
<p style="margin:0 0 10px;">B) O IBAN e outros dados de faturação;</p>
<p style="margin:0 0 10px;">4.3.1.º O pedido de alteração dos dados de faturação deve ser feito pelo/a Sócio/a na receção com uma antecedência mínima de 15 dias.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">5.º - Admissão</h3>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">5.1.ª Admissão</h3>
<p style="margin:0 0 10px;">A inscrição do(a) Sócio(a) apenas produzirá efeitos após:</p>
<p style="margin:0 0 10px;">a) A entrega da documentação solicitada;</p>
<p style="margin:0 0 10px;">b) A aceitação da candidatura pela Kingdom Fight School;</p>
<p style="margin:0 0 10px;">c) O pagamento dos valores inicialmente devidos;</p>
<p style="margin:0 0 10px;">d) A assinatura do presente contrato.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">5.2.ª Recusa da Inscrição</h3>
<p style="margin:0 0 10px;">A Kingdom Fight School poderá recusar fundamentadamente a inscrição quando:</p>
<p style="margin:0 0 10px;">a) Não existam vagas disponíveis;</p>
<p style="margin:0 0 10px;">b) Existam razões objetivas relacionadas com a segurança dos praticantes;</p>
<p style="margin:0 0 10px;">c) O candidato tenha anteriormente praticado infrações disciplinares graves na Kingdom Fight School.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">6.º - Duração</h3>
<p style="margin:0 0 10px;">6.1.º O presente contrato é celebrado pelo período inicial de 1 (um) mês, com início na data indicada na ficha de adesão.</p>
<p style="margin:0 0 10px;">6.2.º Findo o período inicial, o contrato considera-se automaticamente renovado por períodos sucessivos de 1 (um) mês, mantendo-se em vigor enquanto não for validamente denunciado por qualquer das partes, nos termos previstos no presente contrato.</p>
<p style="margin:0 0 10px;">6.3.º Cada período mensal corresponde a um ciclo autónomo de prestação de serviços, sendo devida a respetiva mensalidade nos termos contratualmente estabelecidos.</p>
<p style="margin:0 0 10px;">6.4.º A renovação automática prevista na presente cláusula não prejudica o direito de denúncia do contrato por qualquer das partes, nos termos e prazos estabelecidos nas presentes Condições Gerais de Adesão e na legislação aplicável.</p>
<p style="margin:0 0 10px;">6.5.º A renovação do contrato pressupõe a manutenção das condições essenciais da prestação do serviço, sem prejuízo de eventuais alterações comunicadas ao Sócio(a) nos termos da lei e do presente contrato.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">7.º Pagamento</h3>
<p style="margin:0 0 10px;">7.1.º Pela prestação dos serviços contratados, o(a) Sócio(a) obriga-se ao pagamento dos valores constantes da tabela de preços em vigor à data da adesão.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">7.2.º Poderão existir, designadamente:</h3>
<p style="margin:0 0 10px;">a) taxa de inscrição;</p>
<p style="margin:0 0 10px;">b) mensalidade;</p>
<p style="margin:0 0 10px;">c) taxa federativa, quando aplicável;</p>
<p style="margin:0 0 10px;">d) seguro desportivo;</p>
<p style="margin:0 0 10px;">e) exames de graduação;</p>
<p style="margin:0 0 10px;">f) participação em eventos ou competições;</p>
<p style="margin:0 0 10px;">g) aquisição de equipamento.</p>
<p style="margin:0 0 10px;">7.3.º Todos os valores serão previamente comunicados ao Socio(a) e discriminados na ficha de inscrição.</p>
<p style="margin:0 0 10px;">7.4.º Nenhum pagamento poderá ser exigido relativamente a serviços não solicitados ou previamente contratados pelo(a) Socio(a).</p>
<p style="margin:0 0 10px;">7.5.ª Base mensal. Todos os valores devidos pelo/a Sócio/a a título de quota são fixados numa base mensal. Nos casos em que, em virtude de a data de início, ou de termo, da adesão ou serviço adicional contratado não corresponder ao primeiro ou último dia do mês em curso respetivamente, o valor cobrado pela Kingdom Fight School nos meses em causa corresponderá ao valor proporcional ao período efetivo de duração do contrato ou serviço no mês em causa.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">8.ª Atualização dos Preços</h3>
<p style="margin:0 0 10px;">8.1.º A Kingdom Fight School poderá proceder à atualização dos preços praticados, desde que tal alteração seja objetivamente fundamentada, designadamente por aumento dos custos de funcionamento, atualização do índice de preços no consumidor ou modificação da carga fiscal.</p>
<p style="margin:0 0 10px;">8.2.º Qualquer alteração será comunicada ao Sócio(a), por escrito ou por meio eletrônico, com antecedência mínima de 30 dias relativamente à sua entrada em vigor.</p>
<p style="margin:0 0 10px;">8.3.º Caso não concorde com a atualização proposta, poderá o(a) Sócio(a) denunciar o contrato antes da produção dos respetivos efeitos, sem qualquer penalização.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">Clausula 9.º Forma de pagamento</h3>
<p style="margin:0 0 10px;">9.1.º O pagamento das quantias devidas ao abrigo do presente contrato poderá ser efetuado através de:</p>
<p style="margin:0 0 10px;">a) débito direto;</p>
<p style="margin:0 0 10px;">b) transferência bancária;</p>
<p style="margin:0 0 10px;">c) referência multibanco;</p>
<p style="margin:0 0 10px;">d) numerário;</p>
<p style="margin:0 0 10px;">e) outros meios de pagamento disponibilizados pela Kingdom Fight School.</p>
<p style="margin:0 0 10px;">9.2.º A modalidade de pagamento escolhida pelo(a) Sócio(a) será identificada na ficha de inscrição.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">9.3.º As mensalidades são pagas antecipadamente, até ao dia 5 de cada mês.</h3>
<p style="margin:0 0 10px;">9.4.º O(A) Sócio(a) compromete-se a manter atualizados os dados bancários ou demais elementos necessários à cobrança das quantias devidas.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">10.º Incumprimento do pagamento.</h3>
<p style="margin:0 0 10px;">10.1.º A falta de pagamento de qualquer quantia devida constitui incumprimento contratual.</p>
<p style="margin:0 0 10px;">10.2.º Em caso de mora, a Kingdom Fight School notificará o(a) Sócio(a) para regularizar a situação no prazo de 15 dias.</p>
<p style="margin:0 0 10px;">10.3.º Durante o período de incumprimento, a Kingdom Fight School poderá suspender temporariamente o acesso às aulas e às instalações, sem prejuízo da manutenção da dívida.</p>
<p style="margin:0 0 10px;">10.4.º Persistindo o incumprimento após a notificação prevista no número anterior, poderá a Kingdom Fight School resolver o contrato, nos termos da lei.</p>
<p style="margin:0 0 10px;">10.5.º A resolução do contrato não prejudica o direito da Kingdom Fight School ao recebimento das quantias vencidas até à data da cessação.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">11.º Descontos e Campanhas Promocionais</h3>
<p style="margin:0 0 10px;">11.1.º Os descontos concedidos pela Kingdom Fight School têm natureza promocional e vigoram apenas durante o período expressamente indicado.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">11.2.º Salvo indicação em contrário, os descontos não são cumuláveis.</h3>
<p style="margin:0 0 10px;">11.3.º O termo de uma campanha promocional não confere ao Socio(a) qualquer direito adquirido à manutenção do benefício.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">12.º Suspensão Temporária</h3>
<p style="margin:0 0 10px;">12.1.º O(A) Sócio(a) poderá solicitar a suspensão temporária da sua inscrição, mediante requerimento escrito entregue na receção até ao dia 15 do mês anterior àquele em que se pretende a suspensão.</p>
<p style="margin:0 0 10px;">12.2.º Constituem fundamento para a suspensão, nomeadamente:a) doença ou acidente;b) gravidez;c) deslocação profissional temporária;d) frequência de programa de mobilidade académica;e) outras situações excecionais devidamente comprovadas.</p>
<p style="margin:0 0 10px;">12.3.º A suspensão depende de aceitação pela Kingdom Fight School, salvo quando resulte de imposição legal.</p>
<p style="margin:0 0 10px;">12.4.º Durante a suspensão:a) o(a) Sócio(a) não poderá frequentar as instalações;b) não serão cobradas mensalidades, quando tal resulte das condições da modalidade contratada ou do acordo celebrado entre as partes.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">13.ª Suspensão por Motivos Imputáveis à Academia</h3>
<p style="margin:0 0 10px;">13.1.º Sempre que, por facto imputável à Kingdom Fight School, esta não possa prestar os serviços contratados durante período superior a quinze dias consecutivos, poderá o(a) Sócio(a) optar por:a) suspender temporariamente o contrato;b) obter redução proporcional do preço;c) resolver o contrato, quando a impossibilidade seja definitiva ou de duração incompatível com o interesse do(a) Sócio(a).</p>
<p style="margin:0 0 10px;">13.2.º O disposto no número anterior não se aplica quando a suspensão resulte de casos de força maior ou de determinação das autoridades públicas.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">14.ª Denúncia pelo Aluno</h3>
<p style="margin:0 0 10px;">14.1.º O(A) Sócio(a) pode denunciar o contrato mediante comunicação escrita dirigida à Kingdom Fight School, com antecedência mínima de 30 dias.</p>
<p style="margin:0 0 10px;">14.2.º A denúncia produz efeitos no final do período de faturação em curso, salvo acordo diferente entre as partes.</p>
<p style="margin:0 0 10px;">14.3.º Não poderá ser exigida qualquer penalização pela denúncia além das quantias correspondentes aos serviços efetivamente prestados até à data da produção dos seus efeitos.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">15.ª Resolução por Incumprimento</h3>
<p style="margin:0 0 10px;">15.1.º Qualquer das partes poderá resolver o presente contrato quando ocorra incumprimento grave das obrigações assumidas pela outra parte.</p>
<p style="margin:0 0 10px;">15.2.º Constituem, nomeadamente, fundamento de resolução pela Kingdom Fight School:a) Mora superior a 30 dias no cumprimento de qualquer obrigação pecuniária pelo/a Sócio/a;b) agressões físicas ou verbais;c) destruição intencional de equipamentos;d) prática de comportamentos suscetíveis de colocar em risco a segurança de terceiros;e) violação grave do regulamento interno ou do disposto no presente contrato;</p>
<p style="margin:0 0 10px;">f) prestação de informações erroneas por parte do(a) Sócio(a).</p>
<p style="margin:0 0 10px;">15.2.1.º Resolvido o Contrato pela Kingdom Fight School nos termos da cláusula 15.1.º ou da cláusula 15.2.º, tem esta direito a exigir do/a Sócio/a o pagamento de todos os montantes vencidos e não pagos decorrentes da execução do Contrato, bem como uma indemnização por danos decorrentes do incumprimento e da resolução do Contrato (incluindo honorários e despesas de advogados).</p>
<p style="margin:0 0 10px;">15.3.º Constituem fundamento de resolução pelo(a) Sócio(a):a) encerramento injustificado da Kingdom Fight School;b) incumprimento grave das obrigações de segurança;c) alteração substancial dos serviços contratados sem acordo do(a) Sócio(a);d) incumprimento reiterado dos horários ou serviços essenciais contratados.</p>
<p style="margin:0 0 10px;">15.4.º A resolução deverá ser comunicada por escrito à receção, com indicação dos respetivos fundamentos.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">16.º Impossibilidade Superveniente</h3>
<p style="margin:0 0 10px;">16.1.º Caso o(a) Sócio(a) fique impossibilitado, por motivo permanente e devidamente comprovado, de praticar a modalidade desportiva contratada, poderá requerer a cessação do contrato sem penalização.</p>
<p style="margin:0 0 10px;">16.2.º A Kingdom Fight School poderá solicitar documentação médica suficiente para comprovar a situação invocada, respeitando sempre a legislação relativa à proteção de dados pessoais.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">17.º Direitos do(a) Sócio(a)</h3>
<p style="margin:0 0 10px;">Constituem direitos do(a) Sócio(a):</p>
<p style="margin:0 0 10px;">a) frequentar as aulas e eventos correspondentes à modalidade contratada durante os respetivos horários, com exceção daquela cujo a Kingdom Fight School expressamente faça depender do pagamento de um montante adicional livremente fixado pela Kingdom Fight School;</p>
<p style="margin:0 0 10px;">b) utilizar os equipamentos disponibilizados de acordo com as respetivas regras de utilização;</p>
<p style="margin:0 0 10px;">c) beneficiar de acompanhamento técnico por instrutores qualificados;</p>
<p style="margin:0 0 10px;">d) suspensão da adesão, nos termos contratualmente previstos;</p>
<p style="margin:0 0 10px;">e) utilização de cacifos nos termos contratualmente previstos;</p>
<p style="margin:0 0 10px;">f) ser tratado com respeito, dignidade e igualdade;</p>
<p style="margin:0 0 10px;">g) apresentar reclamações, sugestões ou pedidos de esclarecimento;</p>
<p style="margin:0 0 10px;">h) aceder ao Livro de Reclamações físico ou eletrónico, nos termos da legislação aplicável;</p>
<p style="margin:0 0 10px;">i) obter informação clara relativamente aos serviços prestados e aos preços praticados.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">18.º Obrigações do(a) Sócio(a)</h3>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">18.1.º O(A) Sócio(a) obriga-se a:</h3>
<p style="margin:0 0 10px;">a) preencher o formulário de adesão com informações verdadeiras, completas e atualizadas, comprometendo-se a atualizá-las de imediato sempre que ocorra uma alteração da mesma;</p>
<p style="margin:0 0 10px;">a) cumprir o presente contrato e o regulamento interno;</p>
<p style="margin:0 0 10px;">b) pagar pontualmente as quantias devidas;</p>
<p style="margin:0 0 10px;">c) seguir as recomendações e/ou instruções que lhe forem fornecidas pela Kingdom Fight School, diretamente ou através dos seus representantes, trabalhadores e/ou colaboradores;</p>
<p style="margin:0 0 10px;">c) atuar com urbanidade e educação relativamente a todos os treinadores, colaboradores e demais praticantes;</p>
<p style="margin:0 0 10px;">d) utilizar corretamente os equipamentos;</p>
<p style="margin:0 0 10px;">e) cumprir as normas de higiene e segurança;</p>
<p style="margin:0 0 10px;">f) utilizar o equipamento de proteção exigido para cada modalidade;</p>
<p style="margin:0 0 10px;">g) abster-se de utilizar as instalações e/ou equipamentos da Kingdom Fight School com finalidades lucrativas, exceto se previamente expressamente autorizado/a, por escrito, pela Kingdom Fight School;</p>
<p style="margin:0 0 10px;">h) nos termos e para os efeitos do disposto na Lei n.º 5/2007 de 16 de janeiro (Lei de Bases da Atividade Física e do Desporto) comunicar qualquer condição de saúde que possa influenciar a prática desportiva, na medida estritamente necessária para garantir a segurança da atividade.</p>
<p style="margin:0 0 10px;">18.2.º A violação dos deveres descritos no número anterior constitui justa causa de resolução do presente contrato pela Kingdom Fight School.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">19.º Direitos da Kingdom Fight School</h3>
<p style="margin:0 0 10px;">A Kingdom Fight School tem direito a:</p>
<p style="margin:0 0 10px;">a) receber pontualmente o preço dos serviços prestados;</p>
<p style="margin:0 0 10px;">b) estabelecer horários de funcionamento;</p>
<p style="margin:0 0 10px;">c) organizar turmas e distribuir os praticantes de acordo com critérios técnicos;</p>
<p style="margin:0 0 10px;">d) alterar treinadores, desde que mantenha a qualidade do serviço contratado;</p>
<p style="margin:0 0 10px;">e) aplicar medidas disciplinares previstas no presente contrato e no regulamento interno;</p>
<p style="margin:0 0 10px;">f) suspender temporariamente atividades por razões de segurança, manutenção das instalações ou força maior.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">20.º Princípios Gerais de Segurança</h3>
<p style="margin:0 0 10px;">20.1.º A Kingdom Fight School compromete-se a proporcionar um ambiente de treino seguro, diligenciando pela manutenção adequada das instalações, equipamentos e materiais utilizados nas atividades.</p>
<p style="margin:0 0 10px;">20.2.º Os treinos serão orientados por instrutores devidamente habilitados ou por pessoas cuja qualificação seja legalmente adequada à modalidade praticada.</p>
<p style="margin:0 0 10px;">20.3.º A Kingdom Fight School adotará as medidas razoavelmente exigíveis para prevenir acidentes e minimizar os riscos inerentes à prática desportiva.</p>
<p style="margin:0 0 10px;">20.4.º O(A) Sócio(a) compromete-se a cumprir todas as instruções transmitidas pelos treinadores relativamente à segurança da prática desportiva.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">21.º Aptidão Física</h3>
<p style="margin:0 0 10px;">21.1.º O(A) Sócio(a)declara que, tanto quanto é do seu conhecimento, reúne condições físicas compatíveis com a prática da modalidade em que se inscreve.</p>
<p style="margin:0 0 10px;">21.2.º Sempre que exista qualquer condição clínica suscetível de influenciar a prática desportiva em segurança, o(a) Sócio(a) deverá informar a Kingdom Fight School antes do início das atividades ou logo que essa condição se verifique.</p>
<p style="margin:0 0 10px;">21.3.º A Kingdom Fight School poderá recomendar a apresentação de declaração médica quando, face às circunstâncias concretas, tal seja considerado necessário para salvaguarda da integridade física do(a) próprio(a) Sócio(a) ou de terceiros.</p>
<p style="margin:0 0 10px;">21.4.º A eventual apresentação de declaração médica não transfere para o profissional de saúde nem para a Kingdom Fight School a responsabilidade pela monitorização permanente do estado de saúde do(a) Sócio(a).</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">22.º Riscos Inerentes à Modalidade</h3>
<p style="margin:0 0 10px;">22.1.º O(A) Sócio(a) reconhece que a prática de artes marciais envolve riscos físicos próprios da atividade, designadamente quedas, projeções, entorses, contusões e outras lesões compatíveis com a natureza da modalidade.</p>
<p style="margin:0 0 10px;">22.2.º A participação nos treinos pressupõe a aceitação dos riscos normais e previsíveis da prática desportiva, desde que as atividades decorram de acordo com as regras técnicas e de segurança aplicáveis.</p>
<p style="margin:0 0 10px;">22.3.º O disposto no número anterior não exclui nem limita a responsabilidade da Kingdom Fight School pelos danos decorrentes de dolo, culpa, violação de deveres legais de segurança ou incumprimento contratual.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">23.º Equipamento de Proteção</h3>
<p style="margin:0 0 10px;">23.1.º A utilização de kimonos, luvas, capacetes, caneleiras, protetores bucais ou outro equipamento específico dependerá da modalidade praticada.</p>
<p style="margin:0 0 10px;">23.2.º O(A) Sócio(a) deverá utilizar o equipamento de proteção exigido para cada modalidade.</p>
<p style="margin:0 0 10px;">23.3.º A Kingdom Fight School poderá definir especificações técnicas relativamente ao equipamento considerado adequado.</p>
<p style="margin:0 0 10px;">23.4.º Sempre que a utilização de determinado equipamento seja considerada obrigatória pelo treinador, o(a) Sócio(a) não poderá participar no treino sem esse equipamento.</p>
<p style="margin:0 0 10px;">23.5.º O equipamento individual deverá encontrar-se em boas condições de utilização, higiene e conservação.</p>
<p style="margin:0 0 10px;">23.6.º A utilização de equipamento pertencente à Kingdom Fight School depende da respetiva disponibilidade e deverá respeitar as instruções de utilização transmitidas pelos treinadores.</p>
<p style="margin:0 0 10px;">23.7.º Sempre que exista equipamento oficial da Kingdom Fight School, a respetiva utilização poderá ser exigida apenas em exames, demonstrações públicas ou competições previamente identificadas.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">24.º Interrupção do Treino</h3>
<p style="margin:0 0 10px;">24.1.º O treinador poderá determinar a interrupção imediata da participação do(a) Sócio(a) sempre que verifique:</p>
<p style="margin:0 0 10px;">a) sinais evidentes de lesão;</p>
<p style="margin:0 0 10px;">b) indisposição física;</p>
<p style="margin:0 0 10px;">c) comportamento suscetível de colocar em risco a segurança própria ou de terceiros;</p>
<p style="margin:0 0 10px;">d) utilização inadequada do equipamento;</p>
<p style="margin:0 0 10px;">e) incumprimento das instruções de segurança.</p>
<p style="margin:0 0 10px;">24.2.º A decisão prevista no número anterior constitui medida preventiva e não tem natureza disciplinar.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">25.º Seguro</h3>
<p style="margin:0 0 10px;">25.1.º Sempre que legalmente exigível, a Kingdom Fight School assegurará a existência do seguro desportivo obrigatório.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">25.2.º O(A) Sócio(a) será informado sobre:</h3>
<p style="margin:0 0 10px;">a) a entidade seguradora;</p>
<p style="margin:0 0 10px;">b) o número da apólice;</p>
<p style="margin:0 0 10px;">c) as coberturas;</p>
<p style="margin:0 0 10px;">d) os capitais seguros;</p>
<p style="margin:0 0 10px;">e) as franquias eventualmente aplicáveis.</p>
<p style="margin:0 0 10px;">25.3.º A participação em competições poderá depender da existência de seguro específico, quando exigido pela federação ou entidade organizadora.</p>
<p style="margin:0 0 10px;">25.4.º O(A) Sócio(a) compromete-se a comunicar imediatamente qualquer acidente ocorrido durante a prática desportiva.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">26.º Acidentes Desportivos</h3>
<p style="margin:0 0 10px;">26.1.º Em caso de acidente, a Kingdom Fight School prestará a assistência inicial compatível com os meios disponíveis.</p>
<p style="margin:0 0 10px;">26.2.º Sempre que necessário, serão contactados os serviços de emergência médica e, tratando-se de menor de idade, o respetivo representante legal.</p>
<p style="margin:0 0 10px;">26.3.º O(A) Sócio(a) compromete-se a colaborar nos procedimentos necessários à participação do sinistro junto da seguradora.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">27.º Responsabilidade Civil</h3>
<p style="margin:0 0 10px;">27.1.º A Kingdom Fight School só se responsabiliza, quer a título contratual quer a título extracontratual, pelas ações e omissões dos seus representantes, funcionários e colaboradores nos termos e nos limites da lei, e quando estes tenham agido com dolo ou culpa grave.</p>
<p style="margin:0 0 10px;">27.2.º A Kingdom Fight School não se responsabiliza pelo uso que o(a) Sócio(a) faça dos cacifos, nem pela guarda ou integridade dos bens lá colocados, sendo o(a) Sócio(a), exclusivamente, responsável pelo cadeado que coloque nos cacifos.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">28.ª Graduações</h3>
<p style="margin:0 0 10px;">28.1.º A participação em exames de graduação depende do preenchimento dos requisitos técnicos definidos pelos instrutores ou, quando aplicável, pela federação respetiva.</p>
<p style="margin:0 0 10px;">28.2.º Os exames poderão estar sujeitos ao pagamento de taxa própria, previamente comunicada ao Sócio(a).</p>
<p style="margin:0 0 10px;">28.3.º A aprovação nos exames depende exclusivamente da avaliação técnica efetuada pelos examinadores competentes.</p>
<p style="margin:0 0 10px;">28.4.º A celebração do presente contrato não confere qualquer direito automático à atribuição de graduações.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">29.ª Competições</h3>
<p style="margin:0 0 10px;">29.1.º A participação em competições oficiais ou particulares depende da decisão técnica da equipa de treinadores e do cumprimento dos requisitos definidos pela entidade organizadora.</p>
<p style="margin:0 0 10px;">29.2.º A inscrição em competições poderá implicar custos adicionais, previamente comunicados ao Sócio(a).</p>
<p style="margin:0 0 10px;">29.3.º O(A) Sócio(a) compromete-se a cumprir os regulamentos desportivos aplicáveis durante todas as competições em que represente a Kingdom Fight School.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">30.º Infrações Disciplinares</h3>
<p style="margin:0 0 10px;">Constituem, designadamente, infrações disciplinares:</p>
<p style="margin:0 0 10px;">a) desrespeito pelos treinadores;</p>
<p style="margin:0 0 10px;">b) agressões físicas ou verbais;</p>
<p style="margin:0 0 10px;">c) discriminação de qualquer natureza;</p>
<p style="margin:0 0 10px;">d) utilização indevida dos equipamentos;</p>
<p style="margin:0 0 10px;">e) prática intencional de técnicas proibidas;</p>
<p style="margin:0 0 10px;">f) consumo de álcool ou substâncias ilícitas nas instalações;</p>
<p style="margin:0 0 10px;">g) danos provocados intencionalmente no património da Kingdom Fight School;</p>
<p style="margin:0 0 10px;">h) comportamento suscetível de colocar em risco outros praticantes.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">31.º Medidas Disciplinares</h3>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">31.1.º As infrações disciplinares poderão determinar:</h3>
<p style="margin:0 0 10px;">a) advertência verbal;</p>
<p style="margin:0 0 10px;">b) advertência escrita;</p>
<p style="margin:0 0 10px;">c) suspensão temporária;</p>
<p style="margin:0 0 10px;">d) exclusão definitiva da Kingdom Fight School.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">31.2.º A medida disciplinar deverá ser proporcional à gravidade da infração.</h3>
<p style="margin:0 0 10px;">31.3.º Antes da aplicação de medida disciplinar de suspensão superior a quinze dias ou de exclusão definitiva, será assegurado ao ALUNO o direito de apresentar a sua versão dos factos.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">32.ª Exclusão</h3>
<p style="margin:0 0 10px;">32.1.º A exclusão definitiva apenas poderá ocorrer em caso de infração grave ou reiterada.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">32.2.º Constituem fundamento bastante para exclusão, designadamente:</h3>
<p style="margin:0 0 10px;">a) agressão dolosa;</p>
<p style="margin:0 0 10px;">b) ameaça grave;</p>
<p style="margin:0 0 10px;">c) furto;</p>
<p style="margin:0 0 10px;">d) destruição intencional de bens;</p>
<p style="margin:0 0 10px;">e) falsificação de documentos;</p>
<p style="margin:0 0 10px;">f) prática de comportamentos suscetíveis de comprometer gravemente a segurança da comunidade desportiva.</p>
<p style="margin:0 0 10px;">32.3.º A exclusão produz efeitos após comunicação escrita fundamentada ao Sócio(a).</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">33.º Praticantes Menores de Idade</h3>
<p style="margin:0 0 10px;">33.1.ª Idade mínima A idade mínima para frequentar a Kingdom Fight School é 10 anos.</p>
<p style="margin:0 0 10px;">33.2.º Sócios dos 10 aos 15 anos estão limitados a participar em aulas adequadas para a respetiva faixa etária, denomiadas aulas “Kids”.</p>
<p style="margin:0 0 10px;">33.3.º A inscrição de menores depende da autorização escrita do respetivo representante legal.</p>
<p style="margin:0 0 10px;">33.4.º O representante legal compromete-se a manter atualizados os contactos telefónicos para emergências.</p>
<p style="margin:0 0 10px;">33.5.º A Kingdom Fight School assegurará especial diligência na supervisão dos menores durante os períodos de treino, sem prejuízo da responsabilidade dos respetivos representantes legais fora desses períodos.</p>
<p style="margin:0 0 10px;">33.6.º A recolha do menor após o término das atividades compete ao respetivo representante legal ou à pessoa previamente autorizada para o efeito.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">34.º Aplicação Móvel da Academia</h3>
<p style="margin:0 0 10px;">34.1.º A Kingdom Fight School disponibiliza aos seus alunos uma aplicação móvel (doravante designada por Aplicação), destinada a facilitar o acesso aos serviços prestados e a melhorar a gestão da atividade desportiva.</p>
<p style="margin:0 0 10px;">34.2.º A utilização da Aplicação poderá ser obrigatória para determinadas funcionalidades essenciais ao funcionamento da Kingdom Fight School, nomeadamente:a) identificação do(a) Sócio(a) e controlo de acessos às instalações;b) marcação, alteração ou cancelamento de aulas;c) consulta dos horários das aulas e eventos;d) receção de comunicações da Kingdom Fight School relacionadas com a prestação dos serviços.</p>
<p style="margin:0 0 10px;">34.3.º A Aplicação poderá ainda disponibilizar funcionalidades complementares, designadamente:a) consulta do plano de treino ou da modalidade praticada;b) acompanhamento da evolução técnica e desportiva;c) registo de presenças;d) histórico de graduações, exames ou avaliações;e) consulta de pagamentos, faturas e mensalidades;f) inscrição em seminários, estágios, competições ou outras atividades promovidas pela Kingdom Fight School;g) acesso a conteúdo pedagógicos, vídeos, regulamentos ou outro material de apoio.</p>
<p style="margin:0 0 10px;">34.4.º As funcionalidades disponibilizadas poderão variar em função da modalidade praticada, do plano de adesão contratado e das atualizações efetuadas pela Kingdom Fight School.</p>
<p style="margin:0 0 10px;">34.5.º O(A) Sócio(a) compromete-se a utilizar a Aplicação de forma diligente, mantendo confidenciais as respetivas credenciais de acesso e não permitindo a sua utilização por terceiros.</p>
<p style="margin:0 0 10px;">34.6.º Sempre que o acesso às instalações seja efetuado através da Aplicação, o(a) Sócio(a) é responsável pela utilização do seu dispositivo móvel, devendo comunicar de imediato à Kingdom Fight School qualquer perda, furto ou utilização indevida que possa comprometer a segurança do acesso.</p>
<p style="margin:0 0 10px;">34.7.º A Kingdom Fight School poderá proceder à atualização ou melhoria das funcionalidades da Aplicação.</p>
<p style="margin:0 0 10px;">34.8.º Os dados pessoais tratados através da Aplicação serão processados nos termos da legislação aplicável em matéria de proteção de dados pessoais, do Regulamento (UE) 2016/679 (RGPD), da Lei n.º 58/2019 e da Política de Privacidade da ACADEMIA.</p>
<p style="margin:0 0 10px;">34.9.º A indisponibilidade temporária da Aplicação por motivos de manutenção, atualização técnica ou ocorrência de falhas informáticas não constitui incumprimento contratual, desde que a Kingdom Fight School adote as medidas razoáveis para restabelecer o serviço com a maior brevidade possível e assegure, sempre que possível, meios alternativos de acesso aos serviços essenciais.</p>
<h3 style="font-size:1rem;font-weight:600;margin:14px 0 8px;">35.ª Política de Privacidade</h3>
<p style="margin:0 0 10px;">35.1.º No preenchimento do Formulário de Adesão, serão solicitados ao/à Sócio/a determinados dados suscetíveis de o identificar (“Dados Pessoais”), que serão tratados pela Kingdom Fight School, no estrito cumprimento da lei.</p>
<p style="margin:0 0 10px;">35.2.º Ao/à Sócio/a são garantidos os seguintes direitos no que respeita aos seus Dados Pessoais: (i) direito de acesso aos dados pessoais, (ii) direito de retificação, (iii) direito de apagamento, (iv) direito à limitação, (v) direito de portabilidade, (vi) direito à oposição e, em especial, (vii), direito a opor-se que os seus dados sejam tratados para fins de marketing direto.</p>
`.trim();
