-- Seed da tabela MissionTemplate (missões padrão KFS).
-- Executar no Supabase SQL Editor se a tabela estiver vazia.
-- Se a tua tabela se chama mission_template (snake_case), troca "MissionTemplate" por mission_template
-- e as colunas por: belt_index, xp_reward, sort_order, is_active, created_at, updated_at.

INSERT INTO "MissionTemplate" (id, name, description, modality, "beltIndex", "xpReward", "sortOrder", "isActive", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid()::text, '5 aulas este mês', 'Marca presença confirmada em pelo menos 5 aulas no mês corrente.', NULL, NULL, 50, 0, true, now(), now()),
  (gen_random_uuid()::text, '10 aulas este mês', 'Completa 10 presenças confirmadas no mês.', NULL, NULL, 90, 1, true, now(), now()),
  (gen_random_uuid()::text, '3 semanas consistentes', 'Treina pelo menos 1x por semana durante 3 semanas seguidas.', NULL, NULL, 60, 2, true, now(), now()),
  (gen_random_uuid()::text, 'Semana perfeita', 'Marca presença em todas as aulas da tua turma durante 1 semana.', NULL, NULL, 75, 3, true, now(), now()),
  (gen_random_uuid()::text, 'Primeira aula', 'Completa a tua primeira aula com presença confirmada.', NULL, 0, 40, 4, true, now(), now()),
  (gen_random_uuid()::text, 'Subir Técnico para 7', 'Alcança nota 7 ou superior na dimensão Técnico.', NULL, NULL, 75, 5, true, now(), now()),
  (gen_random_uuid()::text, 'Subir Mental para 8', 'Alcança nota 8 ou superior na dimensão Mental.', NULL, 4, 85, 6, true, now(), now()),
  (gen_random_uuid()::text, 'Melhorar uma dimensão', 'Aumenta pelo menos 1 ponto numa das 5 dimensões na próxima avaliação.', NULL, NULL, 70, 7, true, now(), now()),
  (gen_random_uuid()::text, 'Pedir feedback ao coach', 'Solicita feedback formal ao instrutor e aplica as recomendações.', NULL, NULL, 40, 8, true, now(), now()),
  (gen_random_uuid()::text, 'IMC Saudável', 'Mantém o IMC dentro da faixa saudável por 2 meses consecutivos.', NULL, NULL, 80, 9, true, now(), now()),
  (gen_random_uuid()::text, 'Atualizar avaliação física', 'Atualiza peso e altura e realiza nova avaliação física.', NULL, NULL, 35, 10, true, now(), now()),
  (gen_random_uuid()::text, 'Ver tema da semana', 'Assiste ao vídeo ou estuda o conteúdo do tema da semana antes da aula.', NULL, NULL, 30, 11, true, now(), now()),
  (gen_random_uuid()::text, 'Completar curso da biblioteca', 'Finaliza um curso completo disponível na biblioteca KFS.', NULL, NULL, 70, 12, true, now(), now()),
  (gen_random_uuid()::text, 'Treinar combo oficial', 'Executa corretamente o combo técnico definido pelo coach no mês.', NULL, 2, 60, 13, true, now(), now()),
  (gen_random_uuid()::text, '7 dias de disciplina', 'Treina ou realiza preparação física 7 dias consecutivos.', NULL, NULL, 65, 14, true, now(), now()),
  (gen_random_uuid()::text, 'Definir e cumprir meta', 'Define uma meta mensal e cumpre-a até ao final do mês.', NULL, NULL, 75, 15, true, now(), now()),
  (gen_random_uuid()::text, 'Trazer um amigo', 'Traz um amigo para uma aula experimental na KFS.', NULL, NULL, 50, 16, true, now(), now()),
  (gen_random_uuid()::text, 'Espírito de equipa', 'Ajuda um colega iniciante durante os treinos (confirmado pelo coach).', NULL, 6, 60, 17, true, now(), now()),
  (gen_random_uuid()::text, '50 joelhadas técnicas', 'Executa 50 joelhadas técnicas com forma correta durante treino específico.', 'MUAY_THAI', 0, 45, 18, true, now(), now()),
  (gen_random_uuid()::text, 'Sparring controlado', 'Participa num sparring técnico mantendo disciplina e controlo.', 'MUAY_THAI', 4, 85, 19, true, now(), now()),
  (gen_random_uuid()::text, '100 jabs perfeitos', 'Executa 100 jabs com técnica correta num treino supervisionado.', 'BOXING', 0, 50, 20, true, now(), now()),
  (gen_random_uuid()::text, 'Defesa ativa', 'Demonstra evolução clara na defesa (slip, esquiva, guarda) avaliada pelo coach.', 'BOXING', 4, 80, 21, true, now(), now()),
  (gen_random_uuid()::text, 'Combo Kick 3 níveis', 'Executa combo com variação de altura (baixo, médio, alto) corretamente.', 'KICKBOXING', 2, 60, 22, true, now(), now()),
  (gen_random_uuid()::text, 'Sparring estratégico', 'Aplica estratégia tática definida antes do round.', 'KICKBOXING', 6, 85, 23, true, now(), now()),
  (gen_random_uuid()::text, 'Pronto para próxima faixa', 'Cumpre todos os critérios técnicos e comportamentais para avaliação de graduação.', NULL, NULL, 100, 24, true, now(), now()),
  (gen_random_uuid()::text, 'Primeiras 3 aulas', 'Completa 3 aulas com presença confirmada.', NULL, 0, 40, 25, true, now(), now()),
  (gen_random_uuid()::text, 'Fundamentos da Guarda', 'Demonstra guarda correta durante toda a aula.', NULL, 0, 35, 26, true, now(), now()),
  (gen_random_uuid()::text, '100 movimentos básicos', 'Executa 100 repetições de golpes básicos com técnica correta.', NULL, 0, 45, 27, true, now(), now()),
  (gen_random_uuid()::text, 'Primeira semana completa', 'Treina 2x na mesma semana.', NULL, 0, 50, 28, true, now(), now()),
  (gen_random_uuid()::text, 'Postura de Guerreiro', 'Mantém postura correta durante os drills técnicos.', NULL, 1, 40, 29, true, now(), now()),
  (gen_random_uuid()::text, 'Combo Iniciante', 'Executa corretamente um combo básico ensinado no mês.', NULL, 2, 60, 30, true, now(), now()),
  (gen_random_uuid()::text, 'Primeira avaliação', 'Realiza tua primeira avaliação oficial do coach.', NULL, 0, 50, 31, true, now(), now()),
  (gen_random_uuid()::text, 'Conhece a KFS', 'Assiste ao vídeo institucional e ao tema da semana.', NULL, 0, 30, 32, true, now(), now()),
  (gen_random_uuid()::text, 'Disciplina 14 dias', 'Treina pelo menos 3x em 14 dias.', NULL, 2, 65, 33, true, now(), now()),
  (gen_random_uuid()::text, 'Mentalidade Iniciante Forte', 'Recebe nota ≥7 em Mental na avaliação.', NULL, 2, 70, 34, true, now(), now()),
  (gen_random_uuid()::text, 'Técnico 8', 'Alcança nota 8 em Técnico.', NULL, NULL, 80, 35, true, now(), now()),
  (gen_random_uuid()::text, 'Tático 8', 'Alcança nota 8 em Tático.', NULL, 4, 85, 36, true, now(), now()),
  (gen_random_uuid()::text, 'Físico 9', 'Alcança nota 9 em Físico.', NULL, 6, 95, 37, true, now(), now()),
  (gen_random_uuid()::text, 'Mental 9', 'Alcança nota 9 em Mental.', NULL, 6, 95, 38, true, now(), now()),
  (gen_random_uuid()::text, 'Teórico 8', 'Alcança nota 8 em Teórico.', NULL, 2, 75, 39, true, now(), now()),
  (gen_random_uuid()::text, 'Evolução Completa', 'Sobe pelo menos 1 ponto em 3 dimensões diferentes.', NULL, NULL, 100, 40, true, now(), now()),
  (gen_random_uuid()::text, 'Radar Equilibrado', 'Todas as dimensões ≥7.', NULL, 4, 90, 41, true, now(), now()),
  (gen_random_uuid()::text, 'Excelência KFS', 'Todas as dimensões ≥8.', NULL, 10, 100, 42, true, now(), now()),
  (gen_random_uuid()::text, 'Recuperação Técnica', 'Recupera uma dimensão abaixo de 6 para ≥7.', NULL, NULL, 70, 43, true, now(), now()),
  (gen_random_uuid()::text, 'Feedback Aplicado', 'Recebe feedback e melhora a nota na avaliação seguinte.', NULL, NULL, 60, 44, true, now(), now()),
  (gen_random_uuid()::text, '20 aulas no mês', 'Treina 20x no mesmo mês.', NULL, 11, 100, 45, true, now(), now()),
  (gen_random_uuid()::text, 'Sparring de Elite', 'Participa em 5 rounds intensos com controle técnico.', NULL, 10, 90, 46, true, now(), now()),
  (gen_random_uuid()::text, 'Liderança no Tatame', 'Orienta atletas iniciantes durante treino.', NULL, 11, 85, 47, true, now(), now()),
  (gen_random_uuid()::text, '30 dias de disciplina', 'Treina 5x por semana durante 4 semanas.', NULL, 12, 100, 48, true, now(), now()),
  (gen_random_uuid()::text, 'Mental Inquebrável', 'Nota 9 ou 10 em Mental.', NULL, 11, 95, 49, true, now(), now()),
  (gen_random_uuid()::text, 'Performance Máxima', 'Nota ≥8 em todas as dimensões.', NULL, 10, 100, 50, true, now(), now()),
  (gen_random_uuid()::text, 'Guardião da Cultura', 'Ajuda na organização ou evento interno da KFS.', NULL, 12, 80, 51, true, now(), now()),
  (gen_random_uuid()::text, 'Mestre Técnico', 'Demonstra domínio avançado de combinações complexas.', NULL, 12, 100, 52, true, now(), now()),
  (gen_random_uuid()::text, '8 aulas no mês', 'Marca 8 presenças confirmadas.', NULL, NULL, 70, 53, true, now(), now()),
  (gen_random_uuid()::text, '12 aulas no mês', 'Marca 12 presenças confirmadas.', NULL, NULL, 90, 54, true, now(), now()),
  (gen_random_uuid()::text, 'Tema do mês', 'Completa o estudo do tema mensal na biblioteca.', NULL, NULL, 40, 55, true, now(), now()),
  (gen_random_uuid()::text, 'Meta mensal cumprida', 'Define e cumpre objetivo pessoal do mês.', NULL, NULL, 75, 56, true, now(), now()),
  (gen_random_uuid()::text, '5 aulas na temporada', 'Completa 5 aulas na temporada.', NULL, NULL, 50, 57, true, now(), now()),
  (gen_random_uuid()::text, 'Primeiro combo oficial', 'Executa o primeiro combo oficial com forma correta.', NULL, NULL, 50, 58, true, now(), now()),
  (gen_random_uuid()::text, 'Tema 1 completo', 'Completa o primeiro tema da biblioteca.', NULL, NULL, 40, 59, true, now(), now()),
  (gen_random_uuid()::text, '15 aulas na temporada', 'Completa 15 aulas na temporada.', NULL, NULL, 90, 60, true, now(), now()),
  (gen_random_uuid()::text, 'Subir 1 dimensão', 'Sobe pelo menos 1 ponto numa dimensão do radar.', NULL, NULL, 80, 61, true, now(), now()),
  (gen_random_uuid()::text, 'Sparring técnico', 'Participa num sparring técnico com controlo.', NULL, 4, 85, 62, true, now(), now()),
  (gen_random_uuid()::text, '30 aulas na temporada', 'Completa 30 aulas na temporada.', NULL, 6, 100, 63, true, now(), now()),
  (gen_random_uuid()::text, 'Radar ≥7 em tudo', 'Alcança pelo menos 7 em todas as dimensões do radar.', NULL, 6, 100, 64, true, now(), now()),
  (gen_random_uuid()::text, 'Liderar iniciante', 'Orienta um iniciante num treino (confirmado pelo coach).', NULL, 10, 90, 65, true, now(), now()),
  (gen_random_uuid()::text, 'Performance 360º', 'Excelência em todas as dimensões (Preta/Dourado).', NULL, 11, 100, 66, true, now(), now()),
  (gen_random_uuid()::text, '90 dias sem desistir', 'Mantém assiduidade e compromisso durante 90 dias.', NULL, NULL, 100, 67, true, now(), now()),
  (gen_random_uuid()::text, 'Guerreiro da Temporada', 'Destaque da temporada (Dourado).', NULL, 12, 100, 68, true, now(), now());
